-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@git.yelpcorp.com:yelp_pre_commit_hooks
    sha: 5b47e536433d7a00aaf19a6c403b7ecb6e961634
    hooks:
    -   id: stop-dollar-html
    -   id: httplib-https-connection
    -   id: use-except-as
    -   id: check_mock_methods
    -   id: byte_order_mark
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
