-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
    -   id: check-yaml
    -   id: debug-statements
        language_version: python2.7
    -   id: flake8
        language_version: python2.7
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: name-tests-test
        exclude: tests/helpers/(.+).py
-   repo: git@git.yelpcorp.com:yelp_pre_commit_hooks
    sha: c6f992c816f37415b6a2c256839e85819a2d698f
    hooks:
    -   id: stop-dollar-html
    -   id: httplib-https-connection
    -   id: use-except-as
    -   id: check_mock_methods
        language_version: python2.7
    -   id: byte_order_mark
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: 8b583ac1beb0dd0f14c4bceb0a53bb1023cb3dd7
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
